### ISSUE TITLE
Worth refactoring to ES5?

### ISSUE THREAD

**Issue by DenisCarriere** [w8r/avl#10]
Might be worth looking into simply refactoring this repo to pure ES5, that way you could eliminate the entire Rollup build process (nothing against Rollup), but this repo doesn't seem very large and I think there's more lines of code in the Rollup config then actual lines of source code.

A good example of simple ES5 Class based library is [`rbush`](https://github.com/mourner/rbush/blob/master/index.js) (pretty sure you know this one already 😄).

**Comment by w8r** [comment]
well, I just used the `class` syntax sugar for readability, the rest I wanted to keep under full control. Maybe you are right, but I don't know how to make it export es6 module as well

**Comment by DenisCarriere** [comment]
>  I just used the class syntax sugar for readability

Definitely sugar 😄 It's really not too bad writing it in pure ES5.

> make it export es6 module as well

Also struggling with that part, your library would export as a CommonJS library, and for those using Rollup they would need to use [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs) in their config (which isn't the end of the world since a lot of modules still export as CommonJS). All the other bundles don't have any issues with CommonJS libraries (`babel`, `browserify`, `webpack`).

**Comment by w8r** [comment]
that's what `d3` is using 
https://github.com/d3/d3-geo-projection/blob/master/package.json#L24
```js
{
  ...
  "main": "build/d3-geo-projection.js",
  "module": "index",
  "jsnext:main": "index"
}
```
