### ISSUE TITLE
Large node_modules bundle (216K)

### ISSUE THREAD

**Issue by DenisCarriere** [w8r/avl#11]
For a (<500 lines of code) library this is pretty large repo once installed in the `node_modules` (216K).

```
$ du -h node_modules/avl
4.0K    avl/bench
 16K    avl/build
 96K    avl/dist
 24K    avl/src
 48K    avl/tests
216K    avl
```
One thing which helps prevent this is to include `files` in the `package.json` to exclude some of the unwanted files.

Or refactoring to pure ES5 would make the repo roughly ~24KB

```json
{
  "name": "avl",
  "version": "1.3.0",
  "author": "Alexander Milevski <info@w8r.name>",
  "license": "MIT",
  "description": "AVL tree",
  "main": "dist/avl.js",
  "jsnext:main": "index",
  "module": "src/index",
  "types": "src/index.d.ts",
  "files": [
    "src",
    "dist"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/w8r/avl.git"
  },
```

**Comment by w8r** [comment]
Which one do you suggest? I'd prefer "files"

**Comment by DenisCarriere** [comment]
👍 files is a good start :) I can send over a PR for that

**Comment by DenisCarriere** [comment]
Add `files` to package.json
