### ISSUE TITLE
Tree is not a function

### ISSUE THREAD

**Issue by shobishani** [w8r/avl#29]
I am seeing an error
 `TypeError: Tree is not a function`
I am using it in react after importing it.
import Tree from 'avl';

**Comment by w8r** [comment]
Which webpack version do you use?

**Comment by shobishani** [comment]
Currently I am using 

> Webpack 4.30.0

**Comment by shobishani** [comment]
In src/findIntersections.js
I updated the code to this 
`**var Tree = require('avl/dist/avl'),**`
   ` Sweepline = require('./sweepline'),`
    `Point = require('./point'),`
    `utils = require('./utils');`

Then it worked because I can import Tree directly in my React project but where you have importing from compiled one works `**avl/dist/avl**` works fine
