### ISSUE TITLE
isEmpty() doesnt seem to work

### ISSUE THREAD

**Issue by nh916** [w8r/avl#31]
I'm using the tree and a few times i have been checking for is empty and I have been getting true when there is one node still in there so i have to do tree.size >= 1 instead. If we can get the isEmpty function to work all the better because i hate hard coding anything. Cheers mate!

**Comment by w8r** [comment]
It's hard to reproduce.
https://runkit.com/w8r/5e203b022e2a1c001a6343fc

**Comment by nh916** [comment]
i think the reason it didnt work for me was because i was bumping into async stuff in js, where its running things in different order. would tagging the isEmpty() function with async help the problem?
