### ISSUE TITLE
Typescript definition? :)

### ISSUE THREAD

**Issue by DenisCarriere** [w8r/avl#8]
@w8r Willing to host a Typescript definition built-in this repo or want me to push one to DefinitelyTyped?

Shouldn't be too complicated of a Type definition.

**Comment by DenisCarriere** [comment]
Ops, didn't even notice it here https://github.com/w8r/avl/blob/master/src/index.d.ts

Usually I see them at the root of the project 👍

**Comment by w8r** [comment]
I've all the code in `src` there, didn't want to create an empty export file in the root, does it matter? If it's better this way for TypeScript people, I can move it

**Comment by DenisCarriere** [comment]
No it's good the way it is, as long as it's properly defined in the `package.json` it doesn't matter where it is, usually stays close to the `index.js`.

I always assume there's no Typescript definition :) but in this case there was! 👍
